#!/system/bin/sh

LOGFILE=$1

paths=`ls -d /sys/block/* 2>/dev/null`

sysset () {
    if [ -e "$2" ]; then
        echo "-- echo $1 > $2" | tee -a $LOGFILE
        echo "$1" > "$2"
    else
        echo "-- $2 does not exist" | tee -a $LOGFILE
    fi
}

for S in $paths; do
    sysset 0 $S/queue/rotational
		sysset 0 $S/queue/iostats
		sysset 1 $S/queue/rq_affinity
		sysset 256 $S/queue/nr_requests
		sysset 2 $S/queue/nomerges
		sysset cfq $S/queue/scheduler
		sysset 0 $S/queue/add_random
		sysset 4 $S/bdi/min_ratio
		sysset 100 $S/bdi/max_ratio
done

sysset 200 /sys/block/mmcblk0/queue/iosched/target_latency
