#!/system/bin/sh

LOGFILE=$1
BB=/system/xbin/busybox

sysset () {
    if [ -e "$2" ]; then
        echo "-- echo $1 > $2" | tee -a $LOGFILE
        echo "$1" > "$2"
    else
        echo "-- $2 does not exist" | tee -a $LOGFILE
    fi
}

sysset interactive /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor
sysset interactive /sys/devices/system/cpu/cpu1/cpufreq/scaling_governor
sysset interactive /sys/devices/system/cpu/cpu2/cpufreq/scaling_governor
sysset interactive /sys/devices/system/cpu/cpu3/cpufreq/scaling_governor
sysset interactive /sys/devices/system/cpu/cpu4/cpufreq/scaling_governor
sysset interactive /sys/devices/system/cpu/cpu5/cpufreq/scaling_governor
sysset interactive /sys/devices/system/cpu/cpu6/cpufreq/scaling_governor
sysset interactive /sys/devices/system/cpu/cpu7/cpufreq/scaling_governor
