#!/system/bin/sh

LOGFILE=$1

sysset () {
    if [ -e "$2" ]; then
        echo "-- echo $1 > $2" | tee -a $LOGFILE
        echo "$1" > "$2"
    else
        echo "-- $2 does not exist" | tee -a $LOGFILE
    fi
}

echo "-- disabling debug of platform devices" | tee -a $LOGFILE
sysset 1 /sys/devices/platform//13900000.mali/debug_level
sysset 0 /sys/devices/platform/13ce0000.mfc0/video4linux/video6/dev_debug
sysset 0 /sys/devices/platform/13ce0000.mfc0/video4linux/video7/dev_debug
sysset 0 /sys/devices/platform/13ce0000.mfc0/video4linux/video8/dev_debug
sysset 0 /sys/devices/platform/13ce0000.mfc0/video4linux/video9/dev_debug
sysset 0 /sys/devices/platform/13b10000.scaler/video4linux/video50/dev_debug
sysset 0 /sys/devices/platform/12ca0000.fimc_is_sensor/video4linux/video101/dev_debug
sysset 0 /sys/devices/platform/12ca0000.fimc_is_sensor/video4linux/video210/dev_debug
sysset 0 /sys/devices/platform/12ca0000.fimc_is_sensor/video4linux/video211/dev_debug
sysset 0 /sys/devices/platform/12ca0000.fimc_is_sensor/video4linux/video212/dev_debug
sysset 0 /sys/devices/platform/12ca0000.fimc_is_sensor/video4linux/video213/dev_debug
sysset 0 /sys/devices/platform/12cb0000.fimc_is_sensor/video4linux/video102/dev_debug
sysset 0 /sys/devices/platform/12cb0000.fimc_is_sensor/video4linux/video214/dev_debug
sysset 0 /sys/devices/platform/12cb0000.fimc_is_sensor/video4linux/video215/dev_debug
sysset 0 /sys/devices/platform/12cb0000.fimc_is_sensor/video4linux/video216/dev_debug
sysset 0 /sys/devices/platform/12cb0000.fimc_is_sensor/video4linux/video217/dev_debug
sysset 0 /sys/devices/platform/12cc0000.fimc_is_sensor/video4linux/video103/dev_debug
sysset 0 /sys/devices/platform/12cc0000.fimc_is_sensor/video4linux/video218/dev_debug
sysset 0 /sys/devices/platform/12cc0000.fimc_is_sensor/video4linux/video219/dev_debug
sysset 0 /sys/devices/platform/12cc0000.fimc_is_sensor/video4linux/video220/dev_debug
sysset 0 /sys/devices/platform/12cc0000.fimc_is_sensor/video4linux/video221/dev_debug
sysset 0 /sys/devices/platform/12ce0000.fimc_is/video4linux/video110/dev_debug
sysset 0 /sys/devices/platform/12ce0000.fimc_is/video4linux/video111/dev_debug
sysset 0 /sys/devices/platform/12ce0000.fimc_is/video4linux/video112/dev_debug
sysset 0 /sys/devices/platform/12ce0000.fimc_is/video4linux/video120/dev_debug
sysset 0 /sys/devices/platform/12ce0000.fimc_is/video4linux/video121/dev_debug
sysset 0 /sys/devices/platform/12ce0000.fimc_is/video4linux/video122/dev_debug
sysset 0 /sys/devices/platform/12ce0000.fimc_is/video4linux/video130/dev_debug
sysset 0 /sys/devices/platform/12ce0000.fimc_is/video4linux/video131/dev_debug
sysset 0 /sys/devices/platform/12ce0000.fimc_is/video4linux/video132/dev_debug
sysset 0 /sys/devices/platform/12ce0000.fimc_is/video4linux/video140/dev_debug
sysset 0 /sys/devices/platform/12ce0000.fimc_is/video4linux/video141/dev_debug
sysset 0 /sys/devices/platform/12ce0000.fimc_is/video4linux/video142/dev_debug
sysset 0 /sys/devices/platform/12ce0000.fimc_is/video4linux/video160/dev_debug
sysset 0 /sys/devices/platform/12ce0000.fimc_is/video4linux/video161/dev_debug
sysset 0 /sys/devices/platform/12ce0000.fimc_is/video4linux/video170/dev_debug
sysset 0 /sys/devices/platform/12ce0000.fimc_is/video4linux/video171/dev_debug
sysset 0 /sys/devices/platform/12ce0000.fimc_is/video4linux/video172/dev_debug
sysset 0 /sys/devices/platform/12ce0000.fimc_is/video4linux/video173/dev_debug
sysset 0 /sys/devices/platform/12ce0000.fimc_is/video4linux/video174/dev_debug
sysset 0 /sys/devices/platform/12ce0000.fimc_is/video4linux/video180/dev_debug
sysset 0 /sys/devices/platform/12ce0000.fimc_is/video4linux/video190/dev_debug
sysset 0 /sys/devices/platform/12ce0000.fimc_is/video4linux/video191/dev_debug
sysset 0 /sys/devices/platform/12ce0000.fimc_is/video4linux/video192/dev_debug
sysset 0 /sys/devices/platform/12ce0000.fimc_is/video4linux/video193/dev_debug
