#!/system/bin/sh

LOGFILE=$1

doresetprop () {
    echo "-- resetting property $1 to $2" | tee -a $LOGFILE
    /sbin/resetprop $1 "$2"
}

doresetprop ro.product.model 'Pixel 2 XL'
doresetprop ro.product.brand 'Google'
doresetprop ro.product.manufacturer 'Google'

