#!/system/bin/sh

LOGFILE=$1

sysset () {
    if [ -e "$2" ]; then
        echo "-- echo $1 > $2" | tee -a $LOGFILE
        echo "$1" > "$2"
    else
        echo "-- $2 does not exist" | tee -a $LOGFILE
    fi
}

echo "-- Disable S8 Exynos throttling (DVFS)" | tee -a $LOGFILE
chmod 000 /sys/devices/platform/13900000.mali/dvfs
chmod 000 /sys/devices/platform/13900000.mali/dvfs_max_lock
chmod 000 /sys/devices/platform/13900000.mali/dvfs_min_lock
