#!/system/bin/sh

LOGFILE=$1
PROP=/system/bin/getprop
BB=/system/xbin/busybox

echo "-- applying workqueue tweak" | tee -a $LOGFILE

sysset () {
    if [ -e "$2" ]; then
        echo "-- echo $1 > $2" | tee -a $LOGFILE
        echo "$1" > "$2"
    else
        echo "-- $2 does not exist" | tee -a $LOGFILE
    fi
}

sysset N /sys/module/workqueue/parameters/power_efficient
