#!/system/bin/sh

LOGFILE=$1

CMD=/system/bin/cmd

CNT=0
while [ ! -d /sdcard/Android ]; do
    CNT=$(( $CNT + 1 ))
    sleep 1
    # abort if we slept more than 20 seconds
    if [ "$CNT" -eq 20 ]; then
        echo "-- something is terribly wrong(!), slept for > $CNT seconds waiting for /sdcard/Android" | tee -a $LOGFILE
        echo "<<< Settingsonce ended at $( date +"%Y%m%d - %H:%M:%S" )" | tee -a $LOGFILE
        exit 1
    fi
done
echo "-- slept for $CNT seconds waiting for /sdcard/Android" | tee -a $LOGFILE

echo "-- disabling max volume warning" | tee -a $LOGFILE
$CMD settings put global audio_safe_volume_state 2
$CMD settings put secure unsafe_volume_music_active_ms -1
