#!/system/bin/sh

LOGFILE=$1
PROP=/system/bin/getprop
BB=/system/xbin/busybox
HDPARM=/system/xbin/hdparm

doumount () {
    if [ -d "$1" ]; then
        echo "-- umount $1" | tee -a $LOGFILE
        $BB umount "$1"
    else
        echo "-- $1 does not exist" | tee -a $LOGFILE
    fi
}

doumount /omr
doumount /misc
doumount /preload
