#!/system/bin/sh

LOGFILE=$1
PROP=/system/bin/getprop
BB=/system/xbin/busybox
HDPARM=/system/xbin/hdparm

# had to move this code here ... somehow got reset to 4096 and I can't find out why

$HDPARM -a2048 /dev/block/platform/11120000.ufs/by-name/SYSTEM
echo "-- $HDPARM -a2048 /dev/block/platform/11120000.ufs/by-name/SYSTEM" | tee -a $LOGFILE
$HDPARM -a2048 /dev/block/platform/11120000.ufs/by-name/USERDATA
echo "-- $HDPARM -a2048 /dev/block/platform/11120000.ufs/by-name/USERDATA" | tee -a $LOGFILE
$HDPARM -a2048 /dev/block/platform/11120000.ufs/by-name/CACHE
echo "-- $HDPARM -a2048 /dev/block/platform/11120000.ufs/by-name/CACHE" | tee -a $LOGFILE
