#!/system/bin/sh

LOGFILE=$1
PROP=/system/bin/getprop
BB=/system/xbin/busybox
HDPARM=/system/xbin/hdparm

echo "-- fstrim /system" | tee -a $LOGFILE
$BB fstrim -v /system
echo "-- fstrim /data" | tee -a $LOGFILE
$BB fstrim -v /data
echo "-- fstrim /cache" | tee -a $LOGFILE
$BB fstrim -v /cache
echo "-- fstrim /efs" | tee -a $LOGFILE
$BB fstrim -v /efs


