#!/system/bin/sh

LOGFILE=$1
BB=/system/xbin/busybox

echo "-- changing vm sysctls" | tee -a $LOGFILE
$BB timeout -t 3 -s KILL $BB sysctl -e -w vm.block_dump=0
$BB timeout -t 3 -s KILL $BB sysctl -e -w vm.compact_unevictable_allowed=0
$BB timeout -t 3 -s KILL $BB sysctl -e -w vm.dirty_background_ratio=5
$BB timeout -t 3 -s KILL $BB sysctl -e -w vm.dirty_expire_centisecs=500
$BB timeout -t 3 -s KILL $BB sysctl -e -w vm.dirty_ratio=15
$BB timeout -t 3 -s KILL $BB sysctl -e -w vm.dirty_writeback_centisecs=400
$BB timeout -t 3 -s KILL $BB sysctl -e -w vm.drop_caches=3
$BB timeout -t 3 -s KILL $BB sysctl -e -w vm.laptop_mode=0
$BB timeout -t 3 -s KILL $BB sysctl -e -w vm.min_free_kbytes=16384
$BB timeout -t 3 -s KILL $BB sysctl -e -w vm.min_free_order_shift=4
$BB timeout -t 3 -s KILL $BB sysctl -e -w vm.oom_dump_tasks=0
$BB timeout -t 3 -s KILL $BB sysctl -e -w vm.oom_kill_allocating_task=0
$BB timeout -t 3 -s KILL $BB sysctl -e -w vm.overcommit_memory=1
$BB timeout -t 3 -s KILL $BB sysctl -e -w vm.overcommit_ratio=75
$BB timeout -t 3 -s KILL $BB sysctl -e -w vm.page-cluster=0
$BB timeout -t 3 -s KILL $BB sysctl -e -w vm.panic_on_oom=0
$BB timeout -t 3 -s KILL $BB sysctl -e -w vm.vfs_cache_pressure=100

echo "-- changing debug sysctls" | tee -a $LOGFILE
$BB timeout -t 3 -s KILL $BB sysctl -e -w debug.exception-trace=0

echo "-- changing kernel sysctls" | tee -a $LOGFILE
$BB timeout -t 3 -s KILL $BB sysctl -e -w kernel.compat-log=0
$BB timeout -t 3 -s KILL $BB sysctl -e -w kernel.ctrl-alt-del=1
$BB timeout -t 3 -s KILL $BB sysctl -e -w kernel.dmesg_restrict=0
$BB timeout -t 3 -s KILL $BB sysctl -e -w kernel.hung_task_panic=0
$BB timeout -t 3 -s KILL $BB sysctl -e -w kernel.hung_task_warnings=0
$BB timeout -t 3 -s KILL $BB sysctl -e -w kernel.panic=0
$BB timeout -t 3 -s KILL $BB sysctl -e -w kernel.panic_on_oops=0
$BB timeout -t 3 -s KILL $BB sysctl -e -w kernel.panic_on_stackoverflow=0
$BB timeout -t 3 -s KILL $BB sysctl -e -w kernel.panic_on_warn=0
$BB timeout -t 3 -s KILL $BB sysctl -e -w kernel.perf_cpu_time_max_percent=0
$BB timeout -t 3 -s KILL $BB sysctl -e -w kernel.printk_delay=0
$BB timeout -t 3 -s KILL $BB sysctl -e -w kernel.printk_devkmsg=off
$BB timeout -t 3 -s KILL $BB sysctl -e -w kernel.printk_ratelimit=0
$BB timeout -t 3 -s KILL $BB sysctl -e -w kernel.randomize_va_space=0
$BB timeout -t 3 -s KILL $BB sysctl -e -w kernel.sched_schedstats=0
$BB timeout -t 3 -s KILL $BB sysctl -e -w kernel.softlockup_all_cpu_backtrace=0

echo "-- changing ipv4 sysctls" | tee -a $LOGFILE
$BB timeout -t 3 -s KILL $BB sysctl -e -w net.ipv4.conf.all.accept_redirects=0
$BB timeout -t 3 -s KILL $BB sysctl -e -w net.ipv4.conf.all.accept_source_route=0
$BB timeout -t 3 -s KILL $BB sysctl -e -w net.ipv4.conf.all.rp_filter=2
$BB timeout -t 3 -s KILL $BB sysctl -e -w net.ipv4.conf.all.secure_redirects=0
$BB timeout -t 3 -s KILL $BB sysctl -e -w net.ipv4.conf.default.accept_redirects=0
$BB timeout -t 3 -s KILL $BB sysctl -e -w net.ipv4.conf.default.accept_source_route=0
$BB timeout -t 3 -s KILL $BB sysctl -e -w net.ipv4.conf.default.rp_filter=2
$BB timeout -t 3 -s KILL $BB sysctl -e -w net.ipv4.conf.default.secure_redirects=0
$BB timeout -t 3 -s KILL $BB sysctl -e -w net.ipv4.conf.default.secure_redirects=0
$BB timeout -t 3 -s KILL $BB sysctl -e -w net.ipv4.icmp_echo_ignore_all=1
$BB timeout -t 3 -s KILL $BB sysctl -e -w net.ipv4.icmp_ignore_bogus_error_responses=1
$BB timeout -t 3 -s KILL $BB sysctl -e -w net.ipv4.ip_no_pmtu_disc=0
$BB timeout -t 3 -s KILL $BB sysctl -e -w net.ipv4.route.flush=1
$BB timeout -t 3 -s KILL $BB sysctl -e -w net.ipv4.tcp_ecn=0
$BB timeout -t 3 -s KILL $BB sysctl -e -w net.ipv4.tcp_fack=1
$BB timeout -t 3 -s KILL $BB sysctl -e -w net.ipv4.tcp_fin_timeout=60
$BB timeout -t 3 -s KILL $BB sysctl -e -w net.ipv4.tcp_keepalive_intvl=60
$BB timeout -t 3 -s KILL $BB sysctl -e -w net.ipv4.tcp_keepalive_probes=5
$BB timeout -t 3 -s KILL $BB sysctl -e -w net.ipv4.tcp_keepalive_time=60
$BB timeout -t 3 -s KILL $BB sysctl -e -w net.ipv4.tcp_low_latency=0
$BB timeout -t 3 -s KILL $BB sysctl -e -w net.ipv4.tcp_low_latency=1
$BB timeout -t 3 -s KILL $BB sysctl -e -w net.ipv4.tcp_max_syn_backlog=1024
$BB timeout -t 3 -s KILL $BB sysctl -e -w net.ipv4.tcp_max_tw_buckets=16384
$BB timeout -t 3 -s KILL $BB sysctl -e -w net.ipv4.tcp_moderate_rcvbuf=1
$BB timeout -t 3 -s KILL $BB sysctl -e -w net.ipv4.tcp_moderate_rcvbuf=1
$BB timeout -t 3 -s KILL $BB sysctl -e -w net.ipv4.tcp_no_metrics_save=1
$BB timeout -t 3 -s KILL $BB sysctl -e -w net.ipv4.tcp_no_metrics_save=1
$BB timeout -t 3 -s KILL $BB sysctl -e -w net.ipv4.tcp_rfc1337=1
$BB timeout -t 3 -s KILL $BB sysctl -e -w net.ipv4.tcp_sack=1
$BB timeout -t 3 -s KILL $BB sysctl -e -w net.ipv4.tcp_slow_start_after_idle=0
$BB timeout -t 3 -s KILL $BB sysctl -e -w net.ipv4.tcp_syn_retries=2
$BB timeout -t 3 -s KILL $BB sysctl -e -w net.ipv4.tcp_synack_retries=2
$BB timeout -t 3 -s KILL $BB sysctl -e -w net.ipv4.tcp_syncookies=1
$BB timeout -t 3 -s KILL $BB sysctl -e -w net.ipv4.tcp_timestamps=0
$BB timeout -t 3 -s KILL $BB sysctl -e -w net.ipv4.tcp_tw_recycle=1
$BB timeout -t 3 -s KILL $BB sysctl -e -w net.ipv4.tcp_tw_reuse=1
$BB timeout -t 3 -s KILL $BB sysctl -e -w net.ipv4.tcp_window_scaling=1
$BB timeout -t 3 -s KILL $BB sysctl -e -w net.ipv4.udp_rmem_min=6144
$BB timeout -t 3 -s KILL $BB sysctl -e -w net.ipv4.udp_wmem_min=6144

echo "-- changing ipv6 sysctls" | tee -a $LOGFILE
$BB timeout -t 3 -s KILL $BB sysctl -e -w net.ipv6.ip_no_pmtu_disc=0
$BB timeout -t 3 -s KILL $BB sysctl -e -w net.ipv6.route.flush=1
$BB timeout -t 3 -s KILL $BB sysctl -e -w net.ipv6.tcp_ecn=0
$BB timeout -t 3 -s KILL $BB sysctl -e -w net.ipv6.tcp_fack=1
$BB timeout -t 3 -s KILL $BB sysctl -e -w net.ipv6.tcp_moderate_rcvbuf=1
$BB timeout -t 3 -s KILL $BB sysctl -e -w net.ipv6.tcp_no_metrics_save=1
$BB timeout -t 3 -s KILL $BB sysctl -e -w net.ipv6.tcp_rfc1337=1
$BB timeout -t 3 -s KILL $BB sysctl -e -w net.ipv6.tcp_sack=1
$BB timeout -t 3 -s KILL $BB sysctl -e -w net.ipv6.tcp_timestamps=1
$BB timeout -t 3 -s KILL $BB sysctl -e -w net.ipv6.tcp_window_scaling=1

echo "-- changing file system sysctls" | tee -a $LOGFILE
$BB timeout -t 3 -s KILL $BB sysctl -e -w fs.file-max=524288
$BB timeout -t 3 -s KILL $BB sysctl -e -w fs.inotify.max_queued_events=32768
$BB timeout -t 3 -s KILL $BB sysctl -e -w fs.inotify.max_user_instances=256
$BB timeout -t 3 -s KILL $BB sysctl -e -w fs.inotify.max_user_watches=16384
$BB timeout -t 3 -s KILL $BB sysctl -e -w fs.lease-break-time=15
