#!/system/bin/sh

LOGFILE=$1
PROP=/system/bin/getprop
SERIAL=`cat /efs/FactoryApp/serial_no`
PM=/system/bin/pm
CNT=0

# leave substratum enabled
exit 0

if [ "$SERIAL" == "RF8J90FAC0Y" ]; then
    $PM disable projekt.substratum
    echo "-- disabling projekt.substratum" | tee -a $LOGFILE
else
    echo "-- leaving substratum enabled if it is installed" | tee -a $LOGFILE
fi
