#!/system/bin/sh

LOGFILE=$1
CMD=/system/bin/cmd
PROP=/system/bin/getprop
CNT=0

# enable all overlays which are not yet enabled
for o in `$CMD overlay list | grep '\[ \]' | awk '{print $3}'`; do
    echo "-- enable overlay $o" | tee -a $LOGFILE
    $CMD overlay enable $o
    CNT=$(( $CNT + 1 ))
done
echo "-- $CNT overlays were enabled" | tee -a $LOGFILE
