#!/system/bin/sh

LOGFILE=$1
CNT=0
PM=/system/bin/pm

CNT=0
while [ ! -d /sdcard/Android ]; do
    CNT=$(( $CNT + 1 ))
    sleep 1
    # abort if we slept more than 20 seconds
    if [ "$CNT" -eq 20 ]; then
        echo "-- something is wrong(!), slept for > $CNT seconds waiting for /sdcard/Android" | tee -a $LOGFILE
        echo "<<< Settings ended at $( date +"%Y%m%d - %H:%M:%S" )" | tee -a $LOGFILE
        exit 1
    fi
done
echo "-- slept for $CNT seconds waiting for /sdcard/Android" | tee -a $LOGFILE

# disable the downloadable fonts provider => this wil cause contacts/phone app to use system font instead of downloading Google Sans
$pm disable 'com.google.android.gms/com.google.android.gms.fonts.provider.FontsProvider'
echo "-- disabling com.google.android.gms/com.google.android.gms.fonts.provider.FontsProvider" | tee -a $LOGFILE
