#!/system/bin/sh

LOGFILE=$1
PROP=/system/bin/getprop
BB=/system/xbin/busybox

$BB      mount -o noatime,nodiratime,remount /
echo "-- mount -o noatime,nodiratime,remount /" | tee -a $LOGFILE

$BB      mount -o noatime,nodiratime,nodelalloc,noauto_da_alloc,nobarrier,remount /system
echo "-- mount -o noatime,nodiratime,nodelalloc,noauto_da_alloc,nobarrier,remount /system" | tee -a $LOGFILE

$BB      mount -o noatime,nodiratime,remount /data
echo "-- mount -o noatime,nodiratime,remount /data" | tee -a $LOGFILE

$BB      mount -o noatime,nodiratime,remount /cache
echo "-- mount -o noatime,nodiratime,remount /cache" | tee -a $LOGFILE

$BB      mount -o noatime,nodiratime,remount /efs
echo "-- mount -o noatime,nodiratime,remount /efs" | tee -a $LOGFILE

$BB      mount -o noatime,nodiratime,remount /storage
echo "-- mount -o noatime,nodiratime,remount /storage" | tee -a $LOGFILE

$BB      mount -o noatime,nodiratime,remount /sbin
echo "-- mount -o noatime,nodiratime,remount /sbin" | tee -a $LOGFILE

$BB      mount -o noatime,nodiratime,nodelalloc,noauto_da_alloc,nobarrier,remount /sbin/.core/mirror/system
echo "-- mount -o noatime,nodiratime,nodelalloc,noauto_da_alloc,nobarrier,remount /sbin/.core/mirror/system" | tee -a $LOGFILE

$BB      mount -o noatime,nodiratime,remount /sbin/.core/mirror/bin
echo "-- mount -o noatime,nodiratime,remount /sbin/.core/mirror/bin" | tee -a $LOGFILE

$BB      mount -o noatime,nodiratime,nodelalloc,noauto_da_alloc,nobarrier,remount /sbin/.core/img
echo "-- mount -o noatime,nodiratime,nodelalloc,noauto_da_alloc,nobarrier,remount /sbin/.core/img" | tee -a $LOGFILE
