#!/system/bin/sh

LOGFILE=$1
RM=/system/bin/rm
FIND=/system/bin/find

echo "-- Deleting directories from /data" | tee -a $LOGFILE
$RM -rf /data/app-asec/
$RM -rf /data/app-ephemeral/
$RM -rf /data/app-lib/
$RM -rf /data/app-private/
$RM -rf /data/bio/
$RM -rf /data/custom_image/
$RM -rf /data/enc_user/
$RM -rf /data/local/
$RM -rf /data/mptcp/
$RM -rf /data/nfc_log/
$RM -rf /data/otp/
$RM -rf /data/privatemode/
$RM -rf /data/slog/
$RM -rf /data/snd/
$RM -rf /data/ss/
$RM -rf /data/tombstones/
$RM -rf /data/vendor/

echo "-- Deleting cache directories in /data/data" | tee -a $LOGFILE
$FIND /data/data -type d -iname '*cache*' -exec rm -rf {} \;

echo "-- Deleting *.log files" | tee -a $LOGFILE
$FIND /data -type f -name '*.log' -exec rm {} \;

echo "-- Deleting *.apk files in /data/local and /data/dalvik-cache" | tee -a $LOGFILE
$RM -rf /data/local/*.apk
$RM -rf /data/local/tmp/*.apk
$RM -rf /data/dalvik-cache/*.apk
$RM -rf /data/local/*.apk

echo "-- Deleting *.txt files from /data" | tee -a $LOGFILE
$RM -rf /data/system/dropbox/*.txt
$RM -rf /data/*.txt
$RM -rf /data/dalvik-cache/*.txt
$RM -rf /data/data/*.txt
$RM -rf /data/anr/*.txt
$RM -rf /data/log/*.txt
$RM -rf /data/local/*.txt

echo "-- Deleting *.tmp files from /data" | tee -a $LOGFILE
$RM -rf /data/backup/pending/*.tmp
$RM -rf /data/backup/pending/*.tmp
$RM -rf /data/local/tmp/*.txt
$RM -rf /data/last_alog/*.txt
$RM -rf /data/last_kmsg/*.txt
$RM -rf /data/tombstones/*.txt
$RM -rf /data/system/*.txt
$RM -rf /data/system/dropbox/*.txt
$RM -rf /data/system/usagestats/*.txt

echo "-- Deleting misc files from /data" | tee -a $LOGFILE
$RM -rf /data/mlog/*
$RM -rf /data/cache/*.*
$RM -rf /sdcard/LOST.DIR
$RM -rf /data/ota
$RM -rf /data/ota_package
$RM -rf /data/stock_boot*
$RM -rf /data/tombstones/*.*
