# ~/.bashrc: executed by bash(1) for non-login shells.
# see /usr/share/doc/bash/examples/startup-files (in the package bash-doc)
# for examples

# If not running interactively, don't do anything
[ -z "$PS1" ] && return

# don't put duplicate lines in the history. See bash(1) for more options
# don't overwrite GNU Midnight Commander's setting of `ignorespace'.
export HISTCONTROL=$HISTCONTROL${HISTCONTROL+,}ignoredups
# ... or force ignoredups and ignorespace
export HISTCONTROL=ignoreboth
export CONCURRENTY_LEVEL=4
export TERM=linux

# append to the history file, don't overwrite it
shopt -s histappend

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

export PS1='\[\e[0;32m\]android@\h\[\e[1;31m\][\[\e[1;34m\]\w\[\e[1;31m\]]\[\e[0;32m\]\$ \[\e[0;37m\]'

if [ -f /etc/bash/bash_aliases ]; then
    . /etc/bash/bash_aliases
fi

export PAGER='less -X'

alias ls='ls -Fs --color=auto'
alias m='more'


